name: CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.compiler }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            packages: libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libyaml-cpp-dev
            compiler_family: gcc
            compiler: gcc
            cpp-compiler: g++
            cmake_generator: Ninja

          - name: Linux
            os: ubuntu-latest
            packages: libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libyaml-cpp-dev
            compiler_family: clang
            compiler: clang
            cpp-compiler: clang++
            cmake_generator: Ninja

          - name: Windows
            os: windows-latest
            compiler_family: cl
            compiler: ccache cl
            cpp-compiler: ccache cl
            cmake-args: -A Win32
            build-args: "/clp:NoSummary"
            cmake_generator: "Visual Studio 17 2022"

          - name: macOS
            os: macOS-latest
            app-bundle: openxcom.app
            cmake-args: -DCMAKE_PREFIX_PATH=/opt/local
            compiler_family: clang
            compiler: clang
            cpp-compiler: clang++
            cmake_generator: Ninja

    runs-on: ${{ matrix.os }}
    env:
      BUILD_DIR: build
      CMAKE_BUILD_TYPE: Debug
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_MAXSIZE: 1G
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ccache ${{ matrix.packages }}

      - name: Install packages (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja ccache

      - name: Install ccache (macOS)
        if: runner.os == 'macOS'
        run: brew install ccache

      - name: Install packages (macOS)
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
        id: macports
        with:
          parameters: scripts/macports-config.yml

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.compiler_family }}

      - name: Setup environment
        shell: bash
        run: |
          echo "describe=$(git describe)" >> $GITHUB_ENV
          if [ "${{ matrix.name }}" != "Windows" ]; then
            echo "MAYBE_SUDO=sudo" >> $GITHUB_ENV
          fi

      - name: Cmake --help
        run: cmake --help

      - name: Generate project files
        run: |
          cmake -B ${{ env.BUILD_DIR }} . -DENABLE_WARNING=1 ${{ matrix.cmake-args }}
        env:
          CMAKE_GENERATOR: ${{ matrix.cmake_generator }}
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cpp-compiler }}

      - name: Compile source code
        run: |
          cmake --build ${{ env.BUILD_DIR }} -v -- ${{ matrix.build-args }}

        # Note, this is bogus on MacOS, as it installs shaders et al twice.
        # Windows installs under C:/Program Files (x86)/OpenXcom/bin (where the
        # 'bin' is pretty redundant) and Linux installs under various dirs under
        # /usr/local
      - name: Make install
        shell: bash
        run: |
          $MAYBE_SUDO cmake --build ${{ env.BUILD_DIR }} -v --target install

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openxcom_${{ matrix.name }}_${{ matrix.compiler_family }}-${{ env.describe }}
          path: ${{ env.BUILD_DIR }}/${{ matrix.app-bundle || 'bin' }}/**/*

      - name: Show ccache stats and settings
        run: ccache -sp
